[package]
name = "alpaca-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
ollie-rs = { path = "../ollie-rs" }
serde_json = "1.0.140"
tokio = "1.44.1"
regex = "1.10.3"

[dev-dependencies]
tempfile = "3.8.0"
